trainer:
  # Training hyperparams.
  learning_rate: null
  auto_lr_find: False
  max_epochs: 1
  resume_from_checkpoint: null

  # System hyperparams.
  gpus: 1
  num_nodes: 1
  accumulate_grad_batches: 1
  distributed_backend: dp
